version: 0.96.{build}
branches:
  only:
  - master
configuration: Release
platform: x86
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  verbosity: normal
after_build:
  - 7z a %APPVEYOR_BUILD_FOLDER%\PuttyMadness.zip %APPVEYOR_BUILD_FOLDER%\Renci.SshNet\bin\Release\Renci.SshNet.dll %APPVEYOR_BUILD_FOLDER%\PuttyMadness\bin\Release\PuttyMadness.exe %APPVEYOR_BUILD_FOLDER%\PuttyMadnessHotkeyListener\bin\Release\PuttyMadnessHotkeyListener.exe
artifacts:
  - path: PuttyMadness.zip
    name: PuttyMadness.zip
  - path: Setup\bin\Release\PuttyMadness.msi
    name: PuttyMadness.msi
on_success:
  - git config --global user.email "graham@mhn.org"
  - git config --global user.name "Graham Mainwaring"
  - git config --global credential.helper store
  - git config --global push.default simple
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git checkout master
  - ps: .\update-readme.ps1
  - git add README.md
  - git commit -m "[skip ci] Updated README to version %APPVEYOR_BUILD_VERSION%"
  - git tag %APPVEYOR_BUILD_VERSION%
  - git remote set-url origin https://github.com/ghjm/PuttyMadness.git
  - git push --tags
  - git checkout master
  - git merge %APPVEYOR_BUILD_VERSION%
  - git push
